Scraping song names and lyrics from the web
===============================================
```{r load_packages}
library("XML")
library("stringr")
```
```{r scrape_songs}
allthesongs <- data.frame() 

for (i in 1964:2014) { 
     
     # create the URL for each year
     URL <- paste("http://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_",i,sep="")
     
     # parse the HTML
     results <- htmlTreeParse(URL, useInternal=TRUE)
     
     # pull out text from each table row
     billboard_text <- xpathSApply(results, "//table[@class='wikitable sortable']//tr",xmlValue)
     
     # split into three pieces (rank, song name and year)
     split_billboard_text <- str_split_fixed(billboard_text,"\n",3) 
     
     # put artist names into a data frame along with the year it is from
     billboard <- as.data.frame(cbind(split_billboard_text[2:101, ], rep(i,100)), stringsAsFactors=FALSE)
     
     # row bind this year's data to all the data
     allthesongs <- rbind(allthesongs, billboard) 
     
}

colnames(allthesongs) <- c("Rank", "Song", "Artist", "Year")

```

```{r clean_songs}
allthesongs$Song <- gsub("[^[:alnum:] ]", "", allthesongs$Song)
allthesongs$Artist <- gsub("& ", "", allthesongs$Artist) 
# fix accents
    allthesongs$Artist <- gsub("è|Ã", "e", allthesongs$Artist) 
    allthesongs$Artist <- gsub("ý", "y", allthesongs$Artist) 
    allthesongs$Artist <- gsub("ó|ō", "o", allthesongs$Artist)
    allthesongs$Artist <- gsub("-", " ", allthesongs$Artist)
allthesongs$Artist <- gsub("[^[:alnum:] ]", "", allthesongs$Artist)
```

```{r scrape_lyrics}
for (s in 1:length(allthesongs$Song)) {
     
     lyrics <- "Not set yet."
     
     # clean up the artist field to fit in the URL
         artist <- gsub("The ", "", allthesongs$Artist[s])
         
         artist <- strsplit(artist, " featuring | feat | feat. | with | duet | and ")
         
         artist <- unlist(artist)[[1]]
     
     URL2 <- paste("http://metrolyrics.com/",allthesongs$Song[s],"-lyrics-",artist,".html",sep="") 
          
        URL2 <- tolower(gsub(" ","-",URL2)) 
     
     results <- 12
     
     tryCatch({ 
         results <- htmlTreeParse(URL2, useInternal=TRUE, isURL=TRUE) 
         },
     error=function(cond) { 
         message(paste(URL2, "does not exist")) 
        },
     warning=function(cond) { message(paste(URL2, "caused a warning")) },
     finally={ })
     
     if (is.numeric(results)) {
          
          allthesongs$Lyrics[s] <- "None avail."
          
     } else { 
          lyrics <- xpathSApply(results, "//div[@id='lyrics-body-text']", xmlValue)
            
          if (length(lyrics)!=0) { 
            allthesongs$Lyrics[s] <- lyrics[[1]] 
          } else {
              allthesongs$Lyrics[s] <- "None avail."
          }
     }
}

```

```{r fill_missing_lyrics}
# try to get the missing ones from songlyrics.com
for (t in 1:length(allthesongs$Song)) {
    if (allthesongs$Lyrics[t] == "None avail.") {
        
        lyrics <- "Not set yet."
     
     # clean up the artist field to fit in the URL
         #artist <- gsub("The ", "", allthesongs$Artist[t])
         
        artist <- strsplit(allthesongs$Artist[t], " featuring | feat | feat. | with | duet | and ")
        artist <- unlist(artist)[[1]]    
        URL3 <- paste("http://songlyrics.com/",artist,"/",allthesongs$Song[t],"-lyrics",sep="")    
        URL3 <- tolower(gsub(" ","-",URL3)) 

     results <- 12
     
     tryCatch({ 
         results <- htmlTreeParse(URL3, useInternal=TRUE, isURL=TRUE) 
         },
     error=function(cond) { message(paste(URL3, "does not exist")) },
     warning=function(cond) { message(paste(URL3, "caused a warning")) },
     finally={ })
     
     if (is.numeric(results)) { allthesongs$Lyrics[t] <- "None avail."
          
     } else { 
          lyrics <- xpathSApply(results, "//p[@id='songLyricsDiv']", xmlValue)
            
          if (length(lyrics)!=0) {  allthesongs$Lyrics[t] <- lyrics[[1]] 
                                    
          } else {
              allthesongs$Lyrics[t] <- "None avail."
          }
     }
        
    }
}


```

```{r clean_lyrics}
allthesongs$Lyrics <- gsub("\\\n|\\\t"," ",allthesongs$Lyrics)
allthesongs$Lyrics <- tolower(gsub("[^[:alnum:] ]", "", allthesongs$Lyrics))
```


